#!/usr/bin/env node
/**
 * Regenerates src/maps/leafletAsset.ts from the `leaflet` dev dependency.
 *
 * The fallback map (used on Android when no Google Maps key is configured) runs
 * Leaflet inside a WebView. Leaflet is inlined into the page so the map does
 * not depend on a third-party CDN being reachable; only the tiles need the
 * network. Run `node scripts/gen-leaflet.js` after changing the leaflet version.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const dist = path.join(root, 'node_modules', 'leaflet', 'dist');
const pkg = require(path.join(root, 'node_modules', 'leaflet', 'package.json'));

const js = fs.readFileSync(path.join(dist, 'leaflet.js'), 'utf8');
const css = fs.readFileSync(path.join(dist, 'leaflet.css'), 'utf8');

const out = `// GENERATED by scripts/gen-leaflet.js from leaflet@${
  pkg.version
}. Do not edit.
// Leaflet is (c) 2010-2023 Vladimir Agafonkin, (c) 2010-2011 CloudMade, and is
// distributed under the BSD 2-Clause License (see node_modules/leaflet/LICENSE).

export const LEAFLET_VERSION = ${JSON.stringify(pkg.version)};
export const LEAFLET_JS = ${JSON.stringify(js)};
export const LEAFLET_CSS = ${JSON.stringify(css)};
`;

const target = path.join(root, 'src', 'maps', 'leafletAsset.ts');
fs.mkdirSync(path.dirname(target), {recursive: true});
fs.writeFileSync(target, out);
console.log(`wrote ${path.relative(root, target)} (${out.length} bytes)`);
