// Generates src/ui/iconData.ts from the `lucide` package (devDependency).
// Run: node scripts/gen-icons.js   (writes src/ui/iconData.ts)
const fs = require('fs');
const path = require('path');
const {icons} = require('lucide');

const WANTED = `House Route Zap Activity User ArrowLeft ChevronRight ChevronDown ChevronUp ChevronLeft X Check CircleCheck
TriangleAlert Info Search SlidersHorizontal LocateFixed MapPin Navigation Navigation2 Clock Timer Star Heart Bookmark Bell
Settings ShieldCheck Lock CreditCard Wallet Smartphone Receipt FileText QrCode ScanLine Camera Car BatteryCharging Battery
Gauge Plug PlugZap IndianRupee Percent Calendar Users MessageCircle Phone LifeBuoy Wrench Flag Image WifiOff Wifi RefreshCw
Share2 Download Trash2 Plus Minus ArrowRight ArrowUpDown Languages Eye EyeOff Crown Sparkles Coffee Utensils ShoppingBag
CircleParking TrendingUp Sun Moon LogOut CircleQuestionMark Mail Bluetooth Link Leaf Ellipsis Filter ZapOff Hourglass History
Flame Globe Bolt Map Layers CircleDot Wind ThumbsUp ThumbsDown Send Paperclip Copy Pencil Ticket Gift BadgeCheck CircleAlert
CircleX Siren Truck Compass Milestone Repeat Shuffle Scale Tag Banknote Coins Building2 Store Locate Fuel Bed CalendarClock
MapPinned Mountain Hash Cloud Satellite Cable MessageSquareText Headset Shield FileCheck Fingerprint Smile Meh Frown
Toilet CupSoda Power CircleStop FileDown ArrowUp ArrowDown List ListOrdered GripVertical BellRing BellOff
CalendarCheck Target BatteryLow BatteryFull BatteryWarning MapPinOff Pin ReceiptText BadgeIndianRupee UserRound
CircleCheckBig Pause Play Navigation2Off Undo2 Save CirclePlus CircleMinus Clock3 Timer TimerReset`.split(/\s+/).filter(Boolean);

const kebab = s => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/([A-Za-z])([0-9])/g, '$1$2').toLowerCase();
const out = {};
const missing = [];
for (const name of WANTED) {
  const node = icons[name];
  if (!node) { missing.push(name); continue; }
  out[kebab(name)] = node;
}
if (missing.length) { console.error('Missing icons:', missing.join(' ')); process.exit(1); }

const body = Object.entries(out)
  .map(([k, v]) => `  '${k}': ${JSON.stringify(v)},`)
  .join('\n');
const file = `// GENERATED by scripts/gen-icons.js from lucide (ISC licence). Do not edit by hand.
export type IconNode = ReadonlyArray<readonly [string, Readonly<Record<string, string | number>>]>;

export const ICON_DATA = {
${body}
} as const satisfies Record<string, IconNode>;

export type IconName = keyof typeof ICON_DATA;
`;
const target = process.argv[2] || path.join(__dirname, '..', 'src', 'ui', 'iconData.ts');
fs.mkdirSync(path.dirname(target), {recursive: true});
fs.writeFileSync(target, file);
console.log('wrote', target, Object.keys(out).length, 'icons');
